### ISSUE TITLE
App crashes when send video to S3

### ISSUE THREAD

**Issue by IbraTq** [addpipe/Pipe-Android-SDK#1]
Hi pipe.
I read a log, it said
Caused by: java.lang.ClassNotFoundException: Didn't find class "com.squareup.okhttp.OkHttpClient"

So which `okhttp` version for pipe sdk.
How can i config in my gradle ?

Thanks

**Comment by octavn** [comment]
App does not send video directly to S3. It sends it to our web servers and, after it's processed (transcoded, rotated, snapshot, etc.) it gets pushed (by our server side scripts) to our S3 storage and the client's storage.
